change build pipeline

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -119,15 +119,15 @@ jobs:
           go test -coverprofile=coverage.out ./...
           go tool cover -func=coverage.out
 
-      - name: Enforce coverage threshold
-        run: |
-          percent=$(go tool cover -func=coverage.out | grep total: | awk '{print substr($3, 1, length($3)-1)}')
-          echo "Total coverage: $percent%"
-          threshold=80.0
-          if (( $(echo "$percent < $threshold" | bc -l) )); then
-            echo "::error::Test coverage below threshold ($threshold%)"
-            exit 1
-          fi
+#      - name: Enforce coverage threshold #TODO: если нужен % покрытия определенный.
+#        run: |
+#          percent=$(go tool cover -func=coverage.out | grep total: | awk '{print substr($3, 1, length($3)-1)}')
+#          echo "Total coverage: $percent%"
+#          threshold=80.0
+#          if (( $(echo "$percent < $threshold" | bc -l) )); then
+#            echo "::error::Test coverage below threshold ($threshold%)"
+#            exit 1
+#          fi
 
       - name: Upload coverage artifact
         uses: actions/upload-artifact@v4
@@ -147,7 +147,7 @@ jobs:
           go-version: 1.24.2
 
       - name: Build binary
-        run: go build -v -o build/app ./...
+        run: go build -ldflags="-s -w" -trimpath -buildvcs=false -v -o build/app ./...
 
       - name: Upload binary artifact
         uses: actions/upload-artifact@v4
